### Generated by rprotoc. DO NOT EDIT!
### <proto file: CommsMessages.proto>
# //package CommsMessages;
#  
# //import "google/protobuf/csharp_options.proto";
# //
# //option (google.protobuf.csharp_file_options).namespace = "Onewheel.Interface";
# //option (google.protobuf.csharp_file_options).umbrella_classname = "WorldEventsProtos";
# 
# option optimize_for = SPEED;
# 
#   message Ping
#   {
#     required int32 count = 1;
#   }
#   
#   message Register
#   {
#     required string name = 1;
#   }
#   
#   message Registered
#   {
#     required int32 objectid = 1;
#     optional string motd = 2;
#   }
#   
#   message Say 
#   {
#     required int32 from = 1;
#     required int32 target = 2;
#     required string text = 3;
#   }
#   
#   message MapCoords
#   {
#     required int32 x = 1;
#     required int32 y = 2;
#   }
# 
#   message Coords
#   {
#     required float x = 1;
#     required float y = 2;
#   }
# 
#   message BlockPosition
#   {
#     required int32 x = 1;
#     required int32 y = 2;
#   }
#   
#   message Move
#   {
#     required int32 object = 1;
#     required BlockPosition from = 2;
#     required BlockPosition to = 3;
#     optional int32 speed = 4;
#   }
#   
#   message Action
#   {
#     required int32 from = 1;
#     required BlockPosition target = 2;
#     required string what = 3;
#     required string with = 4;
#   }
#   
#   message Block
#   {
#     required BlockPosition location = 1;
#     required int32 type = 2;
#     required ObjectAction action = 3;
#     required BlockPosition destination = 4;
#     required int32 speed = 5;
#   
#     enum ObjectAction {
#       eAdd = 0;
#       eRemove = 1;
#       eMove = 2;
#     }
#   }
# 
#   message EnterMap
#   {
#     required MapCoords mapCoords = 1;
#   }
# 
#   message ExitMap
#   {
#     required MapCoords mapCoords = 1;
#   }
# 
#   message Map
#   {
#     required MapCoords mapCoords = 1;
#     required MapCoords mapSize = 2;
#     required int32 timestamp = 3;
#     repeated int32 data = 4 [packed=true];
#   }
# 
#   enum MsgType {
#     ePing = 1;
#     eRegister = 2;
#     eRegistered  = 3;
#     eSay = 4;
#     eMovement = 5;
#     eAction = 6;
#     eBlock = 7;
#     eEnterMap = 8;
#     eExitMap = 9;
#   }
# 
#   message Header {
#     // Identifies type of following data
#     required int32 msgtype = 1;
#   }
# 
# //service WebService {
# //  rpc RegisterClient (RegisterClientRequest) returns (Status);
# //  rpc Chat (Say) returns (Status);
# //  rpc DoAction (Action) returns (Status);
# //  rpc Move (Movement) returns (Status);
# //}
# 
# //message Person {
# //  required string name = 1;
# //  required int32 id = 2;
# //  optional string email = 3;
# //
# //  enum PhoneType {
# //    MOBILE = 0;
# //    HOME = 1;
# //    WORK = 2;
# //  }
# //
# //  message PhoneNumber {
# //    required string number = 1;
# //    optional PhoneType type = 2 [default = HOME];
# //  }
# //
# //  repeated PhoneNumber phone = 4;
# //}
# // 
# //// Our address book file is just one of these.
# //message AddressBook {
# //  repeated Person person = 1;
# //}
# 
# //message ServerInfoRequest {
# //  required string clientname = 1;
# //  optional int32 number = 2;
# //}
# //
# //message ServerInfoResponse {
# //  required string servername = 1;
# //}
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

::Protobuf::OPTIONS[:"optimize_for"] = :SPEED
class Ping < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :count, 1
end
class Register < ::Protobuf::Message
  defined_in __FILE__
  required :string, :name, 1
end
class Registered < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :objectid, 1
  optional :string, :motd, 2
end
class Say < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :from, 1
  required :int32, :target, 2
  required :string, :text, 3
end
class MapCoords < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :x, 1
  required :int32, :y, 2
end
class Coords < ::Protobuf::Message
  defined_in __FILE__
  required :float, :x, 1
  required :float, :y, 2
end
class BlockPosition < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :x, 1
  required :int32, :y, 2
end
class Move < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :object, 1
  required :BlockPosition, :from, 2
  required :BlockPosition, :to, 3
  optional :int32, :speed, 4
end
class Action < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :from, 1
  required :BlockPosition, :target, 2
  required :string, :what, 3
  required :string, :with, 4
end
class Block < ::Protobuf::Message
  defined_in __FILE__
  required :BlockPosition, :location, 1
  required :int32, :type, 2
  required :ObjectAction, :action, 3
  required :BlockPosition, :destination, 4
  required :int32, :speed, 5
  class ObjectAction < ::Protobuf::Enum
    defined_in __FILE__
    EAdd = value(:eAdd, 0)
    ERemove = value(:eRemove, 1)
    EMove = value(:eMove, 2)
  end
end
class EnterMap < ::Protobuf::Message
  defined_in __FILE__
  required :MapCoords, :mapCoords, 1
end
class ExitMap < ::Protobuf::Message
  defined_in __FILE__
  required :MapCoords, :mapCoords, 1
end
class Map < ::Protobuf::Message
  defined_in __FILE__
  required :MapCoords, :mapCoords, 1
  required :MapCoords, :mapSize, 2
  required :int32, :timestamp, 3
  repeated :int32, :data, 4, :packed => true
end
class MsgType < ::Protobuf::Enum
  defined_in __FILE__
  EPing = value(:ePing, 1)
  ERegister = value(:eRegister, 2)
  ERegistered = value(:eRegistered, 3)
  ESay = value(:eSay, 4)
  EMovement = value(:eMovement, 5)
  EAction = value(:eAction, 6)
  EBlock = value(:eBlock, 7)
  EEnterMap = value(:eEnterMap, 8)
  EExitMap = value(:eExitMap, 9)
end
class Header < ::Protobuf::Message
  defined_in __FILE__
  required :int32, :msgtype, 1
end