### Generated by rprotoc. DO NOT EDIT!
### <proto file: CommsMessages.proto>
# package CommsMessages;
#  
# //import "google/protobuf/csharp_options.proto";
# //
# //option (google.protobuf.csharp_file_options).namespace = "Onewheel.Interface";
# //option (google.protobuf.csharp_file_options).umbrella_classname = "WorldEventsProtos";
# 
# option optimize_for = SPEED;
# 
# //enum MessageTypes {
# //  RegisterClientRequest = 1;
# //  Status = 2;
# //  Message = 3;
# //  Movement = 4;
# //  Action = 5;
# //  Object = 6;
# //}
# 
# message RegisterClientRequest
# {
#   required string name = 1;
# }
# 
# message Status
# {
#   required StatusType status = 1;
#   required string message = 2;
# 
#   enum StatusType {
#     OK = 0;
#     ERROR = 1;
#   }
# }
# 
# message Message 
# {
#   required string from = 1;
#   required string target = 2;
#   required string message = 3;
# }
# 
# message Coords
# {
#   required int32 x = 1;
#   required int32 y = 2;
# }
# 
# message Movement
# {
#   required string object = 1;
#   required Coords from = 2;
#   required Coords to = 3;
#   required int32 speed = 4;
# }
# 
# message Action
# {
#   required string from = 1;
#   required string target = 2;
#   required string what = 3;
#   required string with = 4;
# }
# 
# message Object
# {
#   required Coords location = 1;
#   required int32 type = 2;
#   required ObjectAction action = 3;
#   required Coords destination = 4;
#   required int32 speed = 5;
# 
#   enum ObjectAction {
#     ADD = 0;
#     REMOVE = 1;
#     MOVE = 2;
#   }
# }
# 
# //service WebService {
# //  rpc RegisterClient (RegisterClientRequest) returns (Status);
# //  rpc Chat (Message) returns (Status);
# //  rpc DoAction (Action) returns (Status);
# //  rpc Move (Movement) returns (Status);
# //}
# 
# //message Person {
# //  required string name = 1;
# //  required int32 id = 2;
# //  optional string email = 3;
# //
# //  enum PhoneType {
# //    MOBILE = 0;
# //    HOME = 1;
# //    WORK = 2;
# //  }
# //
# //  message PhoneNumber {
# //    required string number = 1;
# //    optional PhoneType type = 2 [default = HOME];
# //  }
# //
# //  repeated PhoneNumber phone = 4;
# //}
# // 
# //// Our address book file is just one of these.
# //message AddressBook {
# //  repeated Person person = 1;
# //}
# 
# //message ServerInfoRequest {
# //  required string clientname = 1;
# //  optional int32 number = 2;
# //}
# //
# //message ServerInfoResponse {
# //  required string servername = 1;
# //}
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module CommsMessages
  ::Protobuf::OPTIONS[:"optimize_for"] = :SPEED
  class RegisterClientRequest < ::Protobuf::Message
    defined_in __FILE__
    required :string, :name, 1
  end
  class Status < ::Protobuf::Message
    defined_in __FILE__
    required :StatusType, :status, 1
    required :string, :message, 2
    class StatusType < ::Protobuf::Enum
      defined_in __FILE__
      OK = value(:OK, 0)
      ERROR = value(:ERROR, 1)
    end
  end
  class Message < ::Protobuf::Message
    defined_in __FILE__
    required :string, :from, 1
    required :string, :target, 2
    required :string, :message, 3
  end
  class Coords < ::Protobuf::Message
    defined_in __FILE__
    required :int32, :x, 1
    required :int32, :y, 2
  end
  class Movement < ::Protobuf::Message
    defined_in __FILE__
    required :string, :object, 1
    required :Coords, :from, 2
    required :Coords, :to, 3
    required :int32, :speed, 4
  end
  class Action < ::Protobuf::Message
    defined_in __FILE__
    required :string, :from, 1
    required :string, :target, 2
    required :string, :what, 3
    required :string, :with, 4
  end
  class Object < ::Protobuf::Message
    defined_in __FILE__
    required :Coords, :location, 1
    required :int32, :type, 2
    required :ObjectAction, :action, 3
    required :Coords, :destination, 4
    required :int32, :speed, 5
    class ObjectAction < ::Protobuf::Enum
      defined_in __FILE__
      ADD = value(:ADD, 0)
      REMOVE = value(:REMOVE, 1)
      MOVE = value(:MOVE, 2)
    end
  end
end